[project]
name = "hexid"
version = "0.1.0"
description = "A plugin-based file type identifier"
authors = [
  { name="JamsterJava" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "click",
  "rich"
]

[project.scripts]
hexid = "hexid.cli:main"
